POST http://localhost:3003/api/blogs
  Content-Type: application/json

  {
    
"title": "My superblogIIIII",
"author": "AnnuJee",
"url": "www.annujeeblogi.fi",
"likes": 23456
 

  }
###
  POST http://localhost:3003/api/blogs
  Content-Type: application/json

  {
    
"title": "My superblog vol3",
"author": "AnnuJeeTaas",
"url": "www.annujeeblogikaksi.fi",
"likes": 234588856
 

  }