POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubnUiLCJpZCI6IjYwMjk3MzM5MTcxMDFlNjEyNTZkZDIyYyIsImlhdCI6MTYxMzM5OTQwM30.z0-z1BS9Ke6esSj1PDduUF_CX5fHrFel8GfyZdPaxgY

  {
    
"title": "My superblogIIIII",
"author": "AnnuJee",
"url": "www.annujeeblogi.fi",
"likes": 23456,
"userId": "6029733917101e61256dd22c"
 

  }
###
POST http://localhost:3003/api/blogs
Content-Type: application/json

  {
    
"title": "My superblog vol3",
"author": "AnnuJeeTaas",
"url": "www.annujeeblogikaksi.fi",
"likes": 234588856,
 "userId": "6029733917101e61256dd22c"

  }